site_name: Disaster Response
site_url: https://github.com/pschropp/disaster-recovery-project_NLP
repo_url: https://github.com/pschropp/disaster-recovery-project_NLP
repo_name: GitHub
site_author: passl
copyright: passl

nav:
  - Home: index.md
  - Setup: setup.md

theme:
  name: material  # options: 1) comment out for default template 2) readthedocs 3) material. all options following in theme for material only. comment out if using other theme.
  palette:
    scheme: default  # default for light, slate for dark
    primary: blue  # primary color; default is indigo
    accent: blue  # accent color; default is indigo
  icon:
    repo: fontawesome/brands/github
  features:
    - content.code.annotate
plugins:
  - search
  - autorefs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append("src")
          rendering:
            show_source: false
          selection:
            filters:
                - "!^_"  # exclude all members starting with _
                - "^__init__$"  # but always include __init__ modules and methods
            members: true
            inherited_members: true
            new_path_syntax: true
            docstring_style: google
            docstring_options:
              replace_admonitions: true
  #- mermaid2
markdown_extensions:
  - toc:
      permalink: "#"
  - admonition  # activates admonitions
  - def_list  # activates better bucket lists and task lists
  - pymdownx.details  # adds to admonitions
  - pymdownx.magiclink  # enables auto-recognition of links in markdown
  - pymdownx.superfences:  # make sure mermaid code is not just formatted and displayed
      # make exceptions to highlighting of code:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - attr_list  # adds annotations in docstrings and markdown
  - md_in_html  # necessary for annotations
